//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpers.iText7.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helpers.iText7.Resources.TextsResource", typeof(TextsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificamos.
        /// </summary>
        internal static string CertBodyTitle1 {
            get {
                return ResourceManager.GetString("CertBodyTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En constancia se firma a los {0} días de {1} de {2} a solicitud del interesado.
        ///Atentamente,.
        /// </summary>
        internal static string CertClosing {
            get {
                return ResourceManager.GetString("CertClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} de {2} de {3}.
        /// </summary>
        internal static string CertDate {
            get {
                return ResourceManager.GetString("CertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que INALAMBRIA INTERNACIONAL S.A.S identificada con NIT. 830130510-3, presta el servicio de envío de mensajería de texto a través de nuestra plataforma tecnológica IMP 3.0 a.
        /// </summary>
        internal static string CertDeliveredBody1 {
            get {
                return ResourceManager.GetString("CertDeliveredBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y certifica que realizó el envío de mensajes de texto (SMS) a los destinatarios mencionados en esta certificación, previamente autorizados por.
        /// </summary>
        internal static string CertDeliveredBody2 {
            get {
                return ResourceManager.GetString("CertDeliveredBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es de anotar que el contenido de los mensajes es responsabilidad de.
        /// </summary>
        internal static string CertDeliveredBody3 {
            get {
                return ResourceManager.GetString("CertDeliveredBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a continuación, por solicitud de nuestro cliente.
        /// </summary>
        internal static string CertDeliveredBody4 {
            get {
                return ResourceManager.GetString("CertDeliveredBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INALAMBRIA INTERNACIONAL S.A.S procedió a consultar los archivos de respaldo de la operación y certifica:.
        /// </summary>
        internal static string CertDeliveredBody5 {
            get {
                return ResourceManager.GetString("CertDeliveredBody5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señores.
        /// </summary>
        internal static string CertGreeting1 {
            get {
                return ResourceManager.GetString("CertGreeting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad..
        /// </summary>
        internal static string CertGreeting2 {
            get {
                return ResourceManager.GetString("CertGreeting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directora de Operaciones
        ///Email: Vivian.legro@inalambria.com
        ///Móvil: 315 578 5498.
        /// </summary>
        internal static string CertSignature {
            get {
                return ResourceManager.GetString("CertSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivian Paola Legro Gonzalez.
        /// </summary>
        internal static string CertSignatureName {
            get {
                return ResourceManager.GetString("CertSignatureName", resourceCulture);
            }
        }
    }
}
